// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: api/vktest.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountOfUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Array   []int32 `protobuf:"varint,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	AgeFrom int32   `protobuf:"varint,2,opt,name=ageFrom,proto3" json:"ageFrom,omitempty"`
	AgeTo   int32   `protobuf:"varint,3,opt,name=ageTo,proto3" json:"ageTo,omitempty"`
}

func (x *CountOfUsersRequest) Reset() {
	*x = CountOfUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vktest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountOfUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountOfUsersRequest) ProtoMessage() {}

func (x *CountOfUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vktest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountOfUsersRequest.ProtoReflect.Descriptor instead.
func (*CountOfUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_vktest_proto_rawDescGZIP(), []int{0}
}

func (x *CountOfUsersRequest) GetArray() []int32 {
	if x != nil {
		return x.Array
	}
	return nil
}

func (x *CountOfUsersRequest) GetAgeFrom() int32 {
	if x != nil {
		return x.AgeFrom
	}
	return 0
}

func (x *CountOfUsersRequest) GetAgeTo() int32 {
	if x != nil {
		return x.AgeTo
	}
	return 0
}

type CountOfUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool    `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Count *uint64 `protobuf:"varint,2,opt,name=count,proto3,oneof" json:"count,omitempty"`
}

func (x *CountOfUsersResponse) Reset() {
	*x = CountOfUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_vktest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountOfUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountOfUsersResponse) ProtoMessage() {}

func (x *CountOfUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vktest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountOfUsersResponse.ProtoReflect.Descriptor instead.
func (*CountOfUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_vktest_proto_rawDescGZIP(), []int{1}
}

func (x *CountOfUsersResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CountOfUsersResponse) GetCount() uint64 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

var File_api_vktest_proto protoreflect.FileDescriptor

var file_api_vktest_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x5b, 0x0a, 0x13, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x61,
	0x72, 0x72, 0x61, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x67, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61,
	0x67, 0x65, 0x54, 0x6f, 0x22, 0x51, 0x0a, 0x14, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x9a, 0x01, 0x0a, 0x06, 0x56, 0x4b, 0x54, 0x65,
	0x73, 0x74, 0x12, 0x43, 0x0a, 0x0c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x18, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x76, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_vktest_proto_rawDescOnce sync.Once
	file_api_vktest_proto_rawDescData = file_api_vktest_proto_rawDesc
)

func file_api_vktest_proto_rawDescGZIP() []byte {
	file_api_vktest_proto_rawDescOnce.Do(func() {
		file_api_vktest_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_vktest_proto_rawDescData)
	})
	return file_api_vktest_proto_rawDescData
}

var file_api_vktest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_vktest_proto_goTypes = []interface{}{
	(*CountOfUsersRequest)(nil),  // 0: api.CountOfUsersRequest
	(*CountOfUsersResponse)(nil), // 1: api.CountOfUsersResponse
}
var file_api_vktest_proto_depIdxs = []int32{
	0, // 0: api.VKTest.CountOfUsers:input_type -> api.CountOfUsersRequest
	0, // 1: api.VKTest.StreamCountOfUsers:input_type -> api.CountOfUsersRequest
	1, // 2: api.VKTest.CountOfUsers:output_type -> api.CountOfUsersResponse
	1, // 3: api.VKTest.StreamCountOfUsers:output_type -> api.CountOfUsersResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_vktest_proto_init() }
func file_api_vktest_proto_init() {
	if File_api_vktest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_vktest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountOfUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_vktest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountOfUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_vktest_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_vktest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_vktest_proto_goTypes,
		DependencyIndexes: file_api_vktest_proto_depIdxs,
		MessageInfos:      file_api_vktest_proto_msgTypes,
	}.Build()
	File_api_vktest_proto = out.File
	file_api_vktest_proto_rawDesc = nil
	file_api_vktest_proto_goTypes = nil
	file_api_vktest_proto_depIdxs = nil
}
